#!/bin/bash

mkdir -p /factorio
ln -s /factorio/saves /factorio_server/factorio/saves

SETTINGS_FILE=/factorio/server-settings.json
if test -f "$SETTINGS_FILE"; then
    /factorio_server/factorio/bin/x64/factorio --start-server-load-latest --server-settings $SETTINGS_FILE
else
    /factorio_server/factorio/bin/x64/factorio --start-server-load-latest
fi

